scijava/scijava-ui-swing

src/main/java/org/scijava/ui/swing/console/SwingConsolePane.java
If the console window is already visible, it must not take focus
on show() calls because this leads to an unusable desktop if an
application generates continuous output at System.err which triggers
show() by AbstractConsolePane.outputOccurred(e)).
=> SwingConsolePane: do not catch window focus in show if window is visible

src/main/java/org/scijava/ui/swing/widget/SwingNumberWidget.java
This (mostly) ensures the text of a JSpinner is selected on focus. On OSX it
seems to always work with tabs, and mostly work with mouse clicking. However
there does seem to be a race condition where the text selection can be lost,
presumably from the JSPinner firing a validation event after the text field's
selection has been processed.
See https://github.com/scijava/scijava-ui-swing/issues/12 for future work.
=> Add focus listener to JSpinner text

pom.xml, src/main/java/org/scijava/ui/swing/widget/SwingNumberWidget.java
__DO NOT MERGE YET__
Needs the next SJC release, which will fix default values for numeric types.
=> Improve handling of default values

pom.xml, src/main/java/org/scijava/ui/swing/console/SwingConsolePane.java, src/test/java/org/scijava/ui/swing/console/SwingConsolePaneBenchmark.java
This branch updates the Swing output console so that updates happen only on the AWT Event Dispatch Thread (EDT). See [this IRC discussion on #fiji-devel](http://code.imagej.net/chatlogs/fiji-devel?start-date=2015-04-14&end-date=2015-04-15&times=sparse) for further details on the issue being resolved.
@axtimwalde Before merging, I would appreciate if you would test a couple of things:
1. I'd like to know that this change actually does address your issues with output from TrakEM2.
2. Furthermore, I'm worried about the last commit in the series, that attempts to batch the output events. Given the results of some performance benchmarks I did (see the `SwingConsolePaneBenchmark` class, and the explanation in 881065a3f649e197a8cf5536db85e607ed9c70ea), it may not be worth batching the output …
=> Update console on the EDT only

pom.xml, src/main/java/org/scijava/ui/swing/AbstractSwingUI.java, src/main/java/org/scijava/ui/swing/widget/SwingFileListWidget.java, src/main/java/org/scijava/ui/swing/widget/SwingFileWidget.java
This PR depends on https://github.com/scijava/scijava-common/pull/276.
It implements the `chooseFiles` method, adds a new `SwingFileListWidget`, and adds drag-and-drop support to both the new widget and `SwingFileWidget`.
The current remaining issue is that the returned value is a `File` array of size one, with the file name being the `String` representation of the desired file list.
@ctrueden could you have a look at why this doesn't return an array of all files in the list? I couldn't figure out what's wrong...
=> Multiple file input

src/main/java/org/scijava/ui/swing/console/ConsolePanel.java, src/main/java/org/scijava/ui/swing/console/ItemTextPane.java, src/main/java/org/scijava/ui/swing/console/LogFormatter.java, src/main/java/org/scijava/ui/swing/console/LogRecorder.java, src/main/java/org/scijava/ui/swing/console/LogSourcesPanel.java, src/main/java/org/scijava/ui/swing/console/LoggingPanel.java, src/main/java/org/scijava/ui/swing/console/SwingConsolePane.java, src/main/java/org/scijava/ui/swing/console/TextFilterField.java, src/test/java/org/scijava/ui/swing/console/ItemTextPaneTest.java, src/test/java/org/scijava/ui/swing/console/LogFormatterTest.java, src/test/java/org/scijava/ui/swing/console/LogRecorderTest.java, src/test/java/org/scijava/ui/swing/console/LoggingDemo.java
Add features to the scijava console window:
* Text filtering to quickly search stdout, stderr and log messages.
* Filtering of log messages by source and level.
* Use colors to distinguish log messages from stdout and stderr.
Class LoggingPanel can be used by comprehensive plug ins to show only a subset of log messages related to them.
This pull request depends on https://github.com/scijava/scijava-common/pull/255
=> Enhance console window with regard to log messages

src/main/java/org/scijava/ui/swing/widget/SwingNumberWidget.java
This adds mouse wheel scrolling to sliders and scroll bars created with script parameters, e.g.:
```groovy
#@ int (style="slider", min=0, max=10) a
#@ double (style="slider", min=10, max=20) b
#@ int (style="scroll bar", min=20, max=30) c
```
Decrease/increase by scrolling is in integer steps, as those UI widgets currently only support `int` values (while the underlying model as well as the spinner do support floating point decimals as well). See also #31.
=> Let SwingNumberWidget listen for mouse wheel events

src/main/java/org/scijava/ui/swing/widget/SwingFileWidget.java
Fixes https://github.com/imagej/imagej-legacy/issues/178.
=> Fix drag-n-drop and paste behavior of SwingFileWidget

src/main/java/org/scijava/ui/swing/widget/SwingFileListWidget.java
- Set button label to *Add files...* or *Add folder...* depending on widget style
- Added *Add folder content...* button with drag-drop support to allow adding files matching the extensions defined by `style` from a folder and sub-folders
To test the full functionality, use the following script:
```groovy
#@ File[] (style="extensions:tif") fileList
#@ File[] (style="directories") folderList
println fileList
println folderList
```
- use buttons and/or drag-n-drop (onto the list field, or onto the *Add folder content...* button) to populate the list
- double-click on list entries to remove them
=> Improve file list widget

src/main/java/org/scijava/ui/swing/widget/SwingNumberWidget.java
This allows to use non-integer step sizes and ranges in script parameters with `style="slider"` (see https://github.com/scijava/scijava-ui-swing/issues/31).
```groovy
#@ Integer (style="slider", min=0, max=100, stepSize=2) a
#@ Double (style="slider", min=0, max=100, stepSize=1.5) b
#@ Double (style="slider", min=0, max=100, stepSize=20) c
#@ Double (style="slider", min=0, max=1, stepSize=0.1) d
#@ Double (style="slider", min=-10, max=5, stepSize=5) e
#@ Double (style="slider", min=-0.03, max=0.05, stepSize=0.001) f
```
Remaining issues:
=> Let sliders in number widget support floating point numbers

pom.xml, src/main/java/org/scijava/ui/swing/viewer/table/SwingTableDisplayPanel.java, src/main/java/org/scijava/ui/swing/viewer/table/SwingTableDisplayViewer.java
This adds a `DisplayViewer` plugin and a `TableDisplayPanel` implementation to display `org.scijava.table.Table` objects.
The code was migrated from [`imagej-ui-swing`](https://github.com/imagej/imagej-ui-swing/tree/870e9203ef6cc00795f3f47703d40119b3ab590e/src/main/java/net/imagej/ui/swing/viewer/table).
=> Add UI to display org.scijava.table tables

pom.xml
This requires temporary exclusion of the incompatible dependency in scijava-ui-awt.
* The exclusion can be removed once https://github.com/scijava/scijava-ui-awt/pull/1 is merged and released.
* The version pinning can be removed once we have a `pom-scijava` release managing this version (see https://github.com/scijava/pom-scijava/pull/97).
=> Upgrade miglayout-swing

src/main/java/org/scijava/ui/swing/widget/SwingObjectWidget.java
The dropdown list now shows the object names (retrieved by `ObjectService.getName`), while the tooltip shows the object's `toString()` value for each entry.
This allows using arbitrary object parameters (provided the objects have been registered to the `ObjectService` first) as follows:
```
#@ net.imglib2.realtransform.AffineGet affine
println affine
```
This is a follow-up to https://github.com/scijava/scijava-common/pull/374 and <s>will require a new release of `scijava-common` in order to remove the temporary version pinning</s>.
**Edit**: I now removed the version property definition for `scijava-common`, since `pom-scijava-28.0.0` manages `scijava-common-2.82.0`.
=> Support named objects in (Swing)ObjectWidget

src/main/java/org/scijava/ui/swing/widget/SwingColorWidget.java, src/test/java/org/scijava/ui/swing/widget/SwingColorWidgetDemo.java
This PR makes it possible to use parameters of type`ColorRGBA`. Before, when using `ColorRGBA`, the `SwingColorWidget` would return `null` when changing the color because `ColorRGB` cannot be converted to `ColorRGBA` [here](https://github.com/scijava/scijava-common/blob/master/src/main/java/org/scijava/widget/DefaultWidgetModel.java#L166).
I just quickly copied the `SwingColorWidget` and replaced `ColorRGB` with `ColorRGBA` which makes it work (and also possible to assign colors with alpha value). Let me know if there is a cleaner solution and maybe a way to write a test.
=> Add SwingColorAlphaWidget

src/main/java/org/scijava/ui/swing/widget/SwingMessageWidget.java
This replaces `JLabel` by `JEditorPane` to allow HTML rendering including hyperlinks.
We refer to `PlatformService` to open any clicked URLs.
Note that this makes hyperlinks work in `value`, but not in `label` attributes of message (String) parameters. It is therefore a partial fix for #39.
=> SwingMessageWidget: make hyperlinks work

src/main/java/org/scijava/ui/swing/widget/SwingChoiceWidget.java
Currently, JComboBox items are not updated during DynamicCallbacks as noted in the comments of the DynamicCallback example - https://github.com/imagej/tutorials/blob/d3ff8e818bb26cb4713371878b239b36cb7d4877/maven-projects/dynamic-commands/src/main/java/DynamicCallbacks.java#L29-L31
@imagejan suggested implementing JComboBox updates in the doRefresh() method of SwingChoiceWidget to fix this problem on the forum - https://forum.image.sc/t/repaint-scijava-command-ui/42835/2
I quickly wrote a draft of this so that changes in the options of the dialog can update the JComboBox items. This is very useful for situations where you want one JComboBox to change items based on another. 
Maybe there are deeper reasons to not implement a fix in this manner. Also, there might be cleaner implementations, …
=> Update JComboBox choices during SwingChoiceWidget refresh

pom.xml, src/main/java/org/scijava/ui/swing/widget/SwingNumberWidget.java, src/test/java/org/scijava/ui/swing/widget/SwingNumberWidgetDemo.java, src/test/java/org/scijava/ui/swing/widget/SwingNumberWidgetTest.java
This pull request depends on https://github.com/scijava/scijava-common/pull/405 and supersedes #52.
It includes the changes by @BoudewijnvanLangerak (in #52) as a squashed commit.
Changes can be tested with `SwingNumberWidgetDemo` added here, or with the following script:
```groovy
// Automatically generated format
#@ Double (value=0.0000123, persist=false) a
#@ Double (value=0.000123, persist=false) b
#@ Double (value=0.00123, persist=false) c
#@ Double (value=0.0123, persist=false) d
#@ Double (value=0.123, persist=false) e
#@ Double (value=1.23, persist=false) f
#@ Double (value=123, persist=false) g
#@ Double (value=1, min=0.0, max=10.0, stepSize=0.001, persist=false) h
// Specified format
#@ Double (value=0.0123, persist=false, style="format:#.##") i
#@ Double (value=0.0123, …
```
=> Improve number format in SwingNumberWidget

pom.xml, src/main/java/org/scijava/ui/swing/SwingStatusBar.java, src/main/java/org/scijava/ui/swing/task/SwingTaskMonitorComponent.java, src/test/java/org/scijava/ui/swing/task/DemoTask.java
Adds a circular progress bar component to the status bar which  displays the overall progress of all registered tasks created via the scijava task service. When the user clicks on the circular progress bar, a frame containing a table summarizing each task progression is displayed.
Each task is rendered in the table with a custom renderer, displaying a label with the name of the task and its status, a linear progress bar, and, if enabled, a label with an estimation of the remaining time until task completion. The estimation assumes a constant completion speed since the start of the task registration. Additionally, the second column of the table displays a clickable stop icon and which can be used to cancel the task.
Before cancellation, a user confirmation dialog can be enabled or …
=> Adds swing ui which monitors scijava's tasks

src/main/java/org/scijava/ui/swing/task/SwingTaskMonitorComponent.java
Fixing a stupid mistake I made in the previous PR (https://github.com/scijava/scijava-ui-swing/pull/67)
=> fix cancel not called when no user confirmation is required

src/main/java/org/scijava/ui/swing/viewer/table/SwingTableDisplayPanel.java
This ensures horizontal scrollbar is displayed when contents of table too small to fit in view port.
In addition, it implements a contextual menu hosting some basic actions:
- Copy and Select All command (from the JTable action map)
- Delete selected rows command
- Resize command that enlarges column widths to largest cell in the column
Fixes https://github.com/scijava/scijava-ui-swing/issues/62
=> JTable: Fix absence of horizontal scrollbar and add popup menu actions

src/main/java/org/scijava/ui/swing/widget/SwingObjectWidget.java, src/test/java/org/scijava/ui/swing/widget/SwingObjectWidgetTest.java
For Enum parameters, model.getChoices() returns all available enum values by default, so let's just support any model that has valid choices.
This commit also adds a test for SwingObjectWidget, testing Enum parameters as well as Object parameters with and without objects in their object pool.
This PR currently depends on https://github.com/scijava/scijava-common/pull/400 that adds a required `null` check, so that PR should be merged and this one updated with a newer version of `scijava-common`.
Closes https://github.com/scijava/scijava-common/issues/397.
=> Support Enums in SwingObjectWidget

src/main/java/org/scijava/ui/swing/AbstractSwingUI.java, src/main/java/org/scijava/ui/swing/console/ConsolePanel.java, src/main/java/org/scijava/ui/swing/console/ItemTextPane.java, src/main/java/org/scijava/ui/swing/viewer/text/SwingTextDisplayPanel.java
On Linux and Java 8, the imposed font size of 12 renders at an unbearable half on hiDPI screens.
This makes it so that the font size is always the default of the textarea/textpane.
While at it, this also adds some of LogPanel's contextual commands to ConsolePanel
=> Console: Do not used hardwired font sizes

pom.xml, src/main/java/org/scijava/ui/swing/options/OptionsLookAndFeel.java
@ctrueden, this PR is a proposal on how [Flatlaf](https://github.com/JFormDesigner/FlatLaf#flatlaf---flat-look-and-feel) could be used as an _optional_ L&F for Swing components in Fiji/SciJava in direct response to #61. The advantages of FlatLaf L&Fs are discussed in #61, and  include:
- Proper hiDPI scaling under Java 8 (this is mainly relevant to linux nowadays, but still relevant to other OSes: e.g., Native L&F on the mac scales everything without judgment, and so margins and borders become awkwardly exaggerated: this does not happen with FlatFlaf)
- Much more modern and polished 'feel' relative to JVM default options
- Several fixes for current Swing bugs and limitations that will not be fixed upstream
- Many improvements like[ improved submenu …
=> OptionsLookAndFeel: Support for FlatLaf

src/main/java/org/scijava/ui/swing/console/ConsolePanel.java, src/main/java/org/scijava/ui/swing/console/LogSourcesPanel.java, src/main/java/org/scijava/ui/swing/console/LoggingPanel.java, src/main/java/org/scijava/ui/swing/console/SwingConsolePane.java, src/main/java/org/scijava/ui/swing/options/OptionsLookAndFeel.java
This implements a couple of minor improvements related to the new L&F options:
- OptionsLookAndFeel: `setupLookAndFeel()` calls now updateUI
- Console:
- Ensure default font is readable with dark themes (do not use hardwired foreground colors for default fonts)
- Reduce margins of JTabbedPane for better usage of screen real estate
- LogPanel: Replace non-scalable (icon based) button with scalable (font based) button
- More consistent capitalization of menu items
- Do not list inactive accelerators in contextual menu
Some snapshots under light & dark L&Fs:
=> L&F adjustments and improvements

src/main/java/org/scijava/ui/swing/widget/SwingFileWidget.java, src/test/java/org/scijava/ui/swing/widget/SwingFileWidgetTest.java
* Override FileFilter toString() method in SwingFileWidget so that it shows the extension(s) that are filtered by the file choose dialog instead of the standard toString() method
* Related to
* https://github.com/bigdataviewer/bigdataviewer-playground/issues/110
* https://forum.image.sc/t/scijava-command-file-extensions/29869/2
* Before this PR: ![grafik](https://github.com/scijava/scijava-ui-swing/assets/10515534/955209d6-4c5d-4da9-91be-d5c8fee706e1)
* After this PR: ![grafik](https://github.com/scijava/scijava-ui-swing/assets/10515534/3a37c79f-4b0c-4c49-abc0-1e00021d386c)
=> Make file filter show the extension, instead of cryptic stuff
